

module.exports = {
  "navigator" : true,
  "navigator.vendor" : `Google Inc.`,
  "navigator.appName" : `Netscape`,
  "navigator.plugins.length==0" : false,
  "navigator.platform" : `Linux x86_64`,
  "navigator.webdriver" : false,
  "plugin_ext" : `no extention`,
  "ActiveXObject" : false,
  "webkitURL" : true,
  "_phantom" : false,
  "callPhantom" : false,
  "chrome" : true,
  "yandex" : false,
  "opera" : false,
  "opr" : false,
  "safari" : false,
  "awesomium" : false,
  "puffinDevice" : false,
  "__nightmare" : false,
  "domAutomation" : false,
  "domAutomationController" : false,
  "_Selenium_IDE_Recorder" : false,
  "document.__webdriver_script_fn" : false,
  "document.$cdc_asdjflasutopfhvcZLmcfl_" : false,
  "process.version" : false,
  "global.require" : false,
  "global.process" : false,
  "WebAssembly" : true,
  "require('fs')" : false,
  "globalThis==global" : `cannot evaluate`,
  "window.toString()" : `[object Window]`,
  "navigator.cpuClass" : false,
  "navigator.oscpu" : false,
  "navigator.connection" : true,
  "navigator.language=='C'" : `false`,
  "Object.keys(window).length" : 217,
  "window.outerWidth==0" : `false`,
  "window.outerHeight==0" : `false`,
  "window.WebGLRenderingContext" : true,
  "window.constructor.toString()" : `function Window() { [native code] }`,
  "Boolean(typeof process !== 'undefined' && process.versions && process.versions.node)" : `false`,
  "document.documentMode" : `undefined`,
  "eval.toString().length" : `33`,
  "navigator.connection.rtt" : `0`,
  "deviceType" : `desktop`,
  "screen.width" : `1920`,
  "screen.height" : `1080`,
  "eoapi" : false,
  "eoapi_VerifyThis" : false,
  "eoapi_extInvoke" : false,
  "eoWebBrowserDispatcher" : false,
  "window.HIDDEN_CLASS" : false,
  "navigator.mimeTypes.length==2" : `true`,
  "navigator.plugins.length==2" : `false`,
  "window.globalThis" : true,
  "navigator.userAgentData.brands[0].brand" : `Chromium`,
  "navigator.userAgentData.brands[1].brand" : `Google Chrome`,
  "navigator.userAgentData.brands[2].brand" : `;Not A Brand`,
  "navigator.plugins['Microsoft Edge PDF Plugin']" : false,
};
